### ISSUE TITLE
About the Emoji's Style

### ISSUE THREAD

**Issue by newdee** [crimx/hexo-filter-github-emojis#10]
When I used the github-emojis,  I found that the images were shown unnaturally like follows:
![image](https://user-images.githubusercontent.com/12610440/33534245-3fa93bf6-d8e1-11e7-8902-c59a681b209f.png)
and I set the unicode "true" and it works:
```
unicode: true
```

but now I try to use the local-emoji, and it always like follows:
![image](https://user-images.githubusercontent.com/12610440/33534284-974d8164-d8e1-11e7-95fa-1575ba32959b.png)
I don't know how to hide the emojis' words, and I use the hexo blog  with next theme.
Any help is welcome.

**Comment by crimx** [comment]
take a look at #9. An unknown plugin is generating captions for images.

**Comment by newdee** [comment]
OK, I solved it, 
add this code in the head.swig:
```
  emojis: {
      className: '{{ config.githubEmojis.className | default('github-emoji') }}'
    }
```
and add to fancybox's js
```
.not('.group-picture img, .post-gallery img, img.' + CONFIG.emojis.className)
```

**Comment by crimx** [comment]
OK. So it's the fancybox in the next theme that generates the captions right?

**Comment by newdee** [comment]
@crimx  yes
