### ISSUE TITLE
The escape code becomes `<img>`

### ISSUE THREAD

**Issue by anran758** [crimx/hexo-filter-github-emojis#12]
Hello, I encountered a problem.
I would like to direct escape codes `: tada:`,
but the last rendered code is 
`<img class="github-emoji" title="tada" alt="tada" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f389.png?v7" height="20" width="20" />`, 
 I do not want such an effect, what should I do?

**Comment by crimx** [comment]
Update `hexo-filter-github-emojis` to 1.4.4 and follow this instruction https://github.com/crimx/hexo-filter-github-emojis#tag

**Comment by LeeReindeer** [comment]
@anran758 @crimx 
I have figured it out. Just change the regex expression at [line85](https://github.com/crimx/hexo-filter-github-emojis/blob/e52ceb8b18a7b06916b6cb0a887b218d49a7ab92/index.js#L85) to ```/(?<!`):(\w+):(?!`)/ig```.Then it will not match the emoji code wrapped in **`**.
You can test it on [https://regex101.com/r/TZ8DOX/2](https://regex101.com/r/TZ8DOX/2)

**Comment by crimx** [comment]
This is an intended feature. If you don't want `::` for a file just follow the instruction.

**Comment by crimx** [comment]
See v2.0.0 which should address this issue. Closing.
