### ISSUE TITLE
Script data shown in short abstracts

### ISSUE THREAD

**Issue by shimmy568** [crimx/hexo-filter-github-emojis#13]
So I made a short test post and noticed that the script that you inject is being shown in the abstract of the post. Is there a quick fix for this on my end?

![screenshot_20181206_203148](https://user-images.githubusercontent.com/5677311/49622123-47370980-f996-11e8-8b4d-263ed16f7d4d.png)

**Comment by crimx** [comment]
See README for `inject` option.

**Comment by shimmy568** [comment]
Ah, my bad. I tried that but I guess I forgot to clean the db first. Thanks!

**Comment by crimx** [comment]
:tada:
