### ISSUE TITLE
this plugin overwrites the directory of img

### ISSUE THREAD

**Issue by stellarkey** [crimx/hexo-filter-github-emojis#14]
When I installed the plugin and enabled it, all of my photos' directories are been transfered into the directory  under the main site.
**here is an example:**
Markdown source:

> !\[Img\]\(article_name/some_img.png\)

it runs well cause all my photos have been stored in the related article_name folder。
render into HTML:

> https://my_site/article_name/some_img.png

But after intalled the hexo-filter-github-emojis. My HTML represents this:

> https://my_site/some_img.png

it fails to get the resources.

I don't know how to manage this. orz

**Comment by crimx** [comment]
Hi, judging by the the information you provide I don't think this is caused by hexo-filter-github-emojis.

**Comment by stellarkey** [comment]
Not exactly.... when uninstall the hexo-filter-github-emojis, everything gos back to normal.

**Comment by crimx** [comment]
Without a minimum reproducible example, there's not much I could investigate. This is the only code that modifies DOM nodes:

https://github.com/crimx/hexo-filter-github-emojis/blob/975a3244d324353fdc32b777f21630f886711824/index.js#L70-L77

**Comment by stellarkey** [comment]
Ok, thanks! I will try to make it or get more info.
