### ISSUE TITLE
A resource from Github can't be loaded 

### ISSUE THREAD

**Issue by qinyuanpei** [crimx/hexo-filter-github-emojis#15]
我的博客页面无法打开，和这个请求有关系吗？
![image](https://user-images.githubusercontent.com/7688258/54191285-91c5a600-44f0-11e9-979a-53255067ee86.png)

**Comment by crimx** [comment]
你的服务器 header 限制了域名，做博客用应该不需要这么严格。

**Comment by oxdc** [comment]
@qinyuanpei @crimx The URL has been changed from `https://assets-cdn.github.com/images/icons/emoji/unicode/xxxx.png` to `https://github.githubassets.com/images/icons/emoji/unicode/xxxx.png` !

**Comment by qinyuanpei** [comment]
@crimx @oxdc Thanks for your help 👍
