### ISSUE TITLE
插件将所有文本全部转换成了html实体编码。plugin transfers all text to HTML entity coding.

### ISSUE THREAD

**Issue by CoreJa** [crimx/hexo-filter-github-emojis#17]
# 问题描述
插件将所有的文本全部转换为了html实体编码。不影响页面查看，但是影响hexo里的本地搜索功能。
# 问题复现
[我的博客](https://coreja.com/)上左侧导航栏点搜索，搜"&#"就会发现很多文本搜不到，取而代之的是html实体编码。（也就是说当你真的要搜索关键词的时候，只会有一小部分出现，因为其他的都被转换成html实体编码了）
另一种复现的方式是右键，查看源代码（不是检查/审查元素），拖到下面就会发现没有实际的文本，只有html实体编码。
# 期望
希望只将`::`内的emoji转换为html实体编码从而实现emoji表情功能，而不是所有文本。
# 补充
我不是做前端的，js看的有些一知半解，大概知道是将文本转换成html实体编码，这样emoji也是实体编码便可以使用emoji来替换这部分内容。
如果我有空就直接看看怎么改了，不过最近有些忙，麻烦大佬了。
**最后十分感激大佬为hexo开源做贡献！**
# Problem description
Plugin transfers all the text to html entity encoding. It looks all the same, perfectly good, but it would disturb hexo's local search.
# Problem recurring
Click the search button(the one with a magnifier) in the left navigator on [my blog](https://coreja.com/), type "&#". You shall see tons of html entity coding rather than the keywords. (That is to say, when you type what u really want to search, a few of them would appear because the others were display in html entity coding.)
another method to recurrent the problem is to right click somewhere in the page and click show source code.(rather than Inspect element),scroll to the middle of the source code page, you will find the text represents in the html coding.
# Expectation
Hope the transfer work will only effects on the emojis codes that are surround with `::`, rather than all the word in the article.
# One more thing
I am not a front-end coder, javascript sometimes confuses me, so I got the idea that the plugin transform the text to html entity coding thus making emojis visible.
If only I had the time for debugging... But I am busy working on my graduate paper. 
Anyway, **Thank you for your contribution for opensource on hexo platform.**

**Comment by crimx** [comment]
你好，确定是这个插件的问题吗？据我所知这个插件没有做这样的替换。

**Comment by CoreJa** [comment]
确定，因为当我config下不启用这个插件的时候就没有问题了。我刚刚把插件关了并clean后重新deploy到服务器，没有出现描述的问题。

**Comment by crimx** [comment]
这可能是跟某个插件冲突了，或者是文本编码的问题？很可能跟这里有关

https://github.com/crimx/hexo-filter-github-emojis/blob/975a3244d324353fdc32b777f21630f886711824/index.js#L32

因为我现在不用 Hexo 了，之前的博客也没出现这样的问题，所以就不去折腾你的环境了。你可以提 PR 修复或者去掉本插件。

**Comment by CoreJa** [comment]
好的谢谢大佬。刚刚在调试此插件，的确会将文本变成编码。我如果发现问题了再提个pr。

**Comment by CoreJa** [comment]
刚刚调试的时候发现cheerio拿到的data.content是正常的。在`replaceColons($('body')[0], $, emojis)`调用的时候出现问题。然后data被放回了全都编码了的content。
目前猜测和`data['no-emoji']`有关，因为返回的是undefined

**Comment by CoreJa** [comment]
如果可以的话，想请教一下data['no-emoji']是怎样使用的
目前调试的过程中以下两处判断均不符合预期。
https://github.com/crimx/hexo-filter-github-emojis/blob/975a3244d324353fdc32b777f21630f886711824/index.js#L30
这行的目的应该是判断文章是否含有emoji，对没有emoji的文章直接跳过。而在处理一篇我确定没有emoji字符的文章里它仍然返回true并进行了处理。
https://github.com/crimx/hexo-filter-github-emojis/blob/975a3244d324353fdc32b777f21630f886711824/index.js#L56
同上。

**Comment by crimx** [comment]
啊，那应该冲突是在这里了

https://github.com/crimx/hexo-filter-github-emojis/blob/975a3244d324353fdc32b777f21630f886711824/index.js#L75-L77

对比你的搜索插件生成的 HTML 。

`no-emoji`  那个见文档，是一项 front matter 选项，跟这里无关。

**Comment by CoreJa** [comment]
呃的确是这个问题，`no-emoji`是我没注意。的确是替换出了问题。
不过我留意到
https://github.com/crimx/hexo-filter-github-emojis/blob/975a3244d324353fdc32b777f21630f886711824/index.js#L56-L61
这一段即使没有进入到`replaceColons($('body')[0], $, emojis)`方法之前，`$('body').html()`在控制台的输出也是html实体编码。

**Comment by crimx** [comment]
那就是前面第一段 `cheerio.load` 出的问题咯

**Comment by crimx** [comment]
我还是倾向你的 HTML 文本编码在这里产生了冲突，可以检查一下 https://github.com/cheeriojs/cheerio/issues/866

**Comment by CoreJa** [comment]
你是对的，cheerio上issue和我的情况一样。

**Comment by CoreJa** [comment]
`const $ = cheerio.load(data.content)`改为`const $ = cheerio.load(data.content,{decodeEntities: false})`
jquery拿到的元素则没有做html实体编码。

目前测试是没有太大问题。我会再检查一下，没有问题后给你提个pr。
谢谢大佬帮助！

**Comment by CoreJa** [comment]
#18 
感谢大佬指点，话说npm那边是实时更新的吗还是得等一段时间？

**Comment by crimx** [comment]
已发布
