### ISSUE TITLE
Some links of emoji have expired

### ISSUE THREAD

**Issue by liuyib** [crimx/hexo-filter-github-emojis#19]
When I use emojis, e.g. `:heart:`, I get a 404. Thie link base `https://github.githubassets.com/` is ok, but base `https://assets-cdn.github.com/` is wrong. Have considered replacing the link address?

**Comment by crimx** [comment]
Can you make a PR?

**Comment by liuyib** [comment]
> Can you make a PR?

Yeah, I will do it soon.
