### ISSUE TITLE
Can it works on my index page? Thanks.

### ISSUE THREAD

**Issue by spkingr** [crimx/hexo-filter-github-emojis#2]
How can the emojis work on my `index.html` page? Thanks!

**Comment by crimx** [comment]
@spkingr the plugin is intended to work with markdown files. You can try to rename `index.html` to `index.md`

**Comment by crimx** [comment]
@spkingr You don't need a plugin for index.html. Just Check out [readme](https://github.com/crimx/hexo-filter-github-emojis) for generated HTML contents, then manually replace it with [Github Emojis API](https://api.github.com/emojis). For example, you can add a :sparkles: like this:

```html
 <img class="github-emoji" title=":sparkles:" alt=":sparkles:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/2728.png" height="20" width="20">
```

**Comment by spkingr** [comment]
I got it, thanks! 😃

**Comment by crimx** [comment]
Now with the support of Helper you can do this on templates:

```html
<h1><% github_emoji('octocat') %></h1>
```

**Comment by spkingr** [comment]
Thanks very much! I'll have a try. 😃
