### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by jalenzz** [crimx/hexo-filter-github-emojis#24]
想问下为什么通过 `:sparkles:` 使用，会直接显示✨，但按照 README 里的说法，不是应该渲染成 `<span>xxx</span>` 来显示吗，直接显示导致不同设备显示效果不同

如果用 `{% github_emoji :sparkles: %}` 使用会出现背景显示问题
![image](https://user-images.githubusercontent.com/57910033/80277680-3f127200-8723-11ea-8731-6858550f984e.png)

是我的使用有问题吗

**Comment by crimx** [comment]
检查你的网络，Github API 已被墙。

**Comment by jalenzz** [comment]
是在生成的时候挂代理吗，但是为什么通过 `{% github_emoji :sparkles: %}` 使用时能正常生成 `<span>`

**Comment by crimx** [comment]
见 README ，默认会植入一段 JavaScript，在图片失败后显示 emoji 文字。

**Comment by crimx** [comment]
可以把图片放到自己服务器上避免这个问题。

**Comment by crimx** [comment]
> 为什么通过 :sparkles: 使用，会直接显示sparkles

如果生成的 HTML 直接是 emoji 的话考虑是其它插件的作用。

**Comment by jalenzz** [comment]
非常谢谢，检查发现是我使用 `hexo-renderer-markdown-it-plus` 渲染器造成的，现在已经关掉了渲染器自带的 emoji 功能，但是就出现了和前面一样的问题 ，背景显示有问题
![](https://user-images.githubusercontent.com/57910033/80277680-3f127200-8723-11ea-8731-6858550f984e.png)

**Comment by crimx** [comment]
每个人的网站样式不一，可以关掉 inject 选项自行添加 CSS 调整。

**Comment by jalenzz** [comment]
inject 这里已经关了，但是好像不是 css 的问题。
emoji.json 中的链接是 github.githubassets.com 但readme中的是 assets-cdn.github.com
json 中的链接替换后发现就好了

**Comment by crimx** [comment]
嗯，新版的 Github emoji 是 github.githubassets.com ，但我已经不用 Hexo 了所以不好测试。有可能是图片尺寸问题。

**Comment by jalenzz** [comment]
嗯，谢谢啦
用了最笨的方法 background-position 把他弄边上去了，好像没出什么问题

**Comment by jalenzz** [comment]
😭但是出了点问题，作者能不能帮忙看看，谢谢
https://royce2003.top/about/

**Comment by crimx** [comment]
你把 inject 关了就需要补上相应代码。`background-size` 和 `background-position` 要设置为 `contain` 和 `center` 才能进行缩放。`background-repeat` 要 `no-repeat` 禁止重复填充。

**Comment by crimx** [comment]
可以通过[这里](https://developer.mozilla.org/zh-CN/docs/Web/CSS/background)学习。

**Comment by jalenzz** [comment]
嗯，谢谢
