### ISSUE TITLE
Not compatable with my other plugins

### ISSUE THREAD

**Issue by CCCarrion** [crimx/hexo-filter-github-emojis#26]
Use the emojis makes my blog page error 。
![image](https://user-images.githubusercontent.com/15857842/82763454-749d9e80-9e3a-11ea-9f1a-7d59d00eefef.png)
![image](https://user-images.githubusercontent.com/15857842/82763469-9c8d0200-9e3a-11ea-9285-9942042410ae.png)
![image](https://user-images.githubusercontent.com/15857842/82763476-aca4e180-9e3a-11ea-94d9-698c48c01df1.png)
i dont know how to fix it，and if i not use the emojis ，everything work fine。

**Comment by crimx** [comment]
Judging from the first pic it seems like your script element contents are escaped. Could be related to [this issue](https://github.com/jsdom/jsdom/issues/58) but it was [fixed](https://github.com/jsdom/jsdom/pull/359) long ago. Hard to tell which plugin is responsible with limited info.

The second pic is releated to the `inject` option of this plugin. Looks like your other plugins are generating incorrect html content ending with scripts.

**Comment by crimx** [comment]
Now I just realized you were editing a JavaScript file `fireworks.js`.  Just remove the `<script>` and `</script>`. They are meant for html.
