### ISSUE TITLE
在表格中无法显示

### ISSUE THREAD

**Issue by BlueSky01st** [crimx/hexo-filter-github-emojis#28]
原来是这样:
```markdown
| :clock9: `:clock9:` |
```
应该显示为:

| :clock9: `:clock9:` |

但它只显示:

```markdown
| :clock9: `:clock9:` |
```
该怎么办？

**Comment by crimx** [comment]
可能需要在这里做兼容，目前只判断 TEXT_NODE 节点。

https://github.com/crimx/hexo-filter-github-emojis/blob/10e9ba2871b5a1ece2de071aced10666d40fcec0/index.js#L78
