### ISSUE TITLE
no support win10

### ISSUE THREAD

**Issue by forvoid** [crimx/hexo-filter-github-emojis#3]
hi! I want use your plugin but I can't.because the plugin error by os
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

```

**Comment by crimx** [comment]
@forvoid No worry, everything is fine. :ok_hand: This is just a **warning** telling you something is skipped because of os. Just ignore it.

**Comment by forvoid** [comment]
@crimx Thanks! i ' m sorry ask the question that before  serious search answer by google or other web-site。 sincere thanks again!
