### ISSUE TITLE
Update lodash to v 4.17.21

### ISSUE THREAD

**Issue by lorezyra** [crimx/hexo-filter-github-emojis#32]
Need to update `lodash` dependency due to critical vulnerabilities.

https://github.com/crimx/hexo-filter-github-emojis/blob/a5c19ae246e27df76a7ddaaceabf66e5faa6c3b9/package.json#L21-L26

## Reference
- [Regular Expression Denial of Service (ReDoS) in lodash](https://github.com/advisories/GHSA-29mw-wpgm-hmr9)
- [Command Injection in lodash](https://github.com/advisories/GHSA-35jh-r3h4-6jhm)
- [Regular Expression Denial of Service (ReDoS) in lodash](https://github.com/advisories/GHSA-x5rq-j2xg-h7qm)
- [Command Injection in lodash](https://github.com/advisories/GHSA-p6mc-m468-83gw)

**Comment by crimx** [comment]
Thanks for the updates! Lodash removed.
