### ISSUE TITLE
Failed to install github emojis

### ISSUE THREAD

**Issue by de-conf** [crimx/hexo-filter-github-emojis#5]
Hello i am installing github emojis encountered an error, hinted as follows:
`- hexo-filter-github-emojis@1.4.1

Npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules \ chokidar \ node_modules \ fsevents):
Npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os": "darwin", "arch": "any"} (current: {"os": "win32", "arch" "X64"})
How can i solve this problem?

**Comment by crimx** [comment]
Ignore it, It's a *WARN*ing.

**Comment by de-conf** [comment]
ok,thank you!!!
