### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by LucasCtrl** [crimx/hexo-filter-github-emojis#6]
During installation, the load remains blocked for a good minute
![image](https://user-images.githubusercontent.com/19686996/30121378-c81e2060-932b-11e7-9f03-8a15f33f35d4.png)
After i've got this error
![image](https://user-images.githubusercontent.com/19686996/30121471-0b2c8856-932c-11e7-8224-cb7e638466e0.png)
I tried this but nothing happens. I always have the same error
https://stackoverflow.com/a/26606405/7962808

PS: I run the command prompt in administrator mode

**Comment by crimx** [comment]
This error has nothing to do with the package. This should be a npm issue.

I suggest you manually delete the fsevents folder in node_modules and try again. Restart the system if you can.

**Comment by LucasCtrl** [comment]
After the new update of node and npm I try to install the package again. Now it works. The error actually came from node (old version v8.4.0, new version v8.5.0)
