### ISSUE TITLE
Warning after install this script

### ISSUE THREAD

**Issue by newdee** [crimx/hexo-filter-github-emojis#7]
After install the emoji script with npm,  the warning comes out when use hexo  generate and hexo server:
```
DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

**Comment by crimx** [comment]
Fixed. Thanks for the notice.

**Comment by newdee** [comment]
Thanks, I have solved it, just use the `writeFileSync` function instead of `writeFile` function.
The solution on [here](https://newdee.cf/posts/6d87f1ac/)

**Comment by crimx** [comment]
No need to block runtime for simply dumping files.
