### ISSUE TITLE
About the Hexo's "null"

### ISSUE THREAD

**Issue by newdee** [crimx/hexo-filter-github-emojis#8]
Thank you for fix the warning on the last issue I created, now it fixed. but when I install the new emojis script, I always shows the "null" after the hexo's output on the terminal.
 hexo cle
```
INFO  Deleted database.
INFO  Deleted public folder.
null
```
hexo g
```
INFO  Start processing
INFO  Files loaded in 7.92 s
null
```
hexo s
```
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
null
```
And after uninstall hexo-filter-github-emojis, the "null" disappear.

**Comment by crimx** [comment]
Oops... Fixed. Sorry for the inconvenience. Should be more careful.
